package bean;
// Generated 2017-6-2 17:51:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set properties = new HashSet(0);
	private Set products = new HashSet(0);

	public Category() {
	}

	public Category(String name, Set properties, Set products) {
		this.name = name;
		this.properties = properties;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getProperties() {
		return this.properties;
	}

	public void setProperties(Set properties) {
		this.properties = properties;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
