package bean;
// Generated 2017-6-2 17:51:04 by Hibernate Tools 4.3.5.Final

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private Integer id;
	private Order order;
	private Product product;
	private User user;
	private Integer number;

	public Orderitem() {
	}

	public Orderitem(Order order, Product product, User user, Integer number) {
		this.order = order;
		this.product = product;
		this.user = user;
		this.number = number;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
