package bean;
// Generated 2017-6-2 17:51:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productimage generated by hbm2java
 */
public class Productimage implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String type;
	private Set products = new HashSet(0);

	public Productimage() {
	}

	public Productimage(Product product, String type, Set products) {
		this.product = product;
		this.type = type;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
