package bean;
// Generated 2017-6-2 17:51:04 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Productimage productimage;
	private String name;
	private String subTitle;
	private Float orignalPrice;
	private Float promotePrice;
	private Integer stock;
	private Date createDate;
	private Integer reviewCount;
	private Integer saleCount;
	private Integer sealCount;
	private Set productimages = new HashSet(0);
	private Set reviews = new HashSet(0);
	private Set orderitems = new HashSet(0);

	public Product() {
	}

	public Product(Category category, Productimage productimage, String name, String subTitle, Float orignalPrice,
			Float promotePrice, Integer stock, Date createDate, Integer reviewCount, Integer saleCount,
			Integer sealCount, Set productimages, Set reviews, Set orderitems) {
		this.category = category;
		this.productimage = productimage;
		this.name = name;
		this.subTitle = subTitle;
		this.orignalPrice = orignalPrice;
		this.promotePrice = promotePrice;
		this.stock = stock;
		this.createDate = createDate;
		this.reviewCount = reviewCount;
		this.saleCount = saleCount;
		this.sealCount = sealCount;
		this.productimages = productimages;
		this.reviews = reviews;
		this.orderitems = orderitems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Productimage getProductimage() {
		return this.productimage;
	}

	public void setProductimage(Productimage productimage) {
		this.productimage = productimage;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public Float getOrignalPrice() {
		return this.orignalPrice;
	}

	public void setOrignalPrice(Float orignalPrice) {
		this.orignalPrice = orignalPrice;
	}

	public Float getPromotePrice() {
		return this.promotePrice;
	}

	public void setPromotePrice(Float promotePrice) {
		this.promotePrice = promotePrice;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getReviewCount() {
		return this.reviewCount;
	}

	public void setReviewCount(Integer reviewCount) {
		this.reviewCount = reviewCount;
	}

	public Integer getSaleCount() {
		return this.saleCount;
	}

	public void setSaleCount(Integer saleCount) {
		this.saleCount = saleCount;
	}

	public Integer getSealCount() {
		return this.sealCount;
	}

	public void setSealCount(Integer sealCount) {
		this.sealCount = sealCount;
	}

	public Set getProductimages() {
		return this.productimages;
	}

	public void setProductimages(Set productimages) {
		this.productimages = productimages;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set orderitems) {
		this.orderitems = orderitems;
	}

}
