package bean;
// Generated 2017-6-2 17:51:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Property generated by hbm2java
 */
public class Property implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private Set propertyvalues = new HashSet(0);

	public Property() {
	}

	public Property(Category category, String name, Set propertyvalues) {
		this.category = category;
		this.name = name;
		this.propertyvalues = propertyvalues;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPropertyvalues() {
		return this.propertyvalues;
	}

	public void setPropertyvalues(Set propertyvalues) {
		this.propertyvalues = propertyvalues;
	}

}
