package bean;
// Generated 2017-6-2 17:51:04 by Hibernate Tools 4.3.5.Final

/**
 * Propertyvalue generated by hbm2java
 */
public class Propertyvalue implements java.io.Serializable {

	private Integer id;
	private Property property;
	private Integer pid;
	private String value;

	public Propertyvalue() {
	}

	public Propertyvalue(Property property, Integer pid, String value) {
		this.property = property;
		this.pid = pid;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
